
server:
  port: 8080

spring:
  port: 8080
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: true

    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  liquibase:
    enabled: true
    drop-first: false
#    change-log: classpath:liquibase/changelog/changelog.yaml
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
