version: '3.8'
services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
      - liquibase
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  liquibase:
    image: liquibase/liquibase:latest-alpine
    container_name: liquibase
    depends_on:
      - service-db
    command: --url=jdbc:postgresql://service-db:5432/postgres?user=postgres&password=postgres --changeLogFile=/db/changelog/db.changelog-master.yaml update
    volumes:
      - ./db/changelog/db.changelog-master.yaml:/db/changelog/db.changelog-master.yaml

volumes:
  db-data:
